kernel.randomize_va_space = 2
kernel.kptr_restrict = 2
kernel.sched_migration_cost_ns = 5000000
kernel.sched_min_granularity_ns = 500000
kernel.sched_wakeup_granularity_ns = 1000000

# SteamOS default and aim to improve performance
vm.max_map_count = 2147483642
kernel.shmmax = 18446744073709551615
kernel.shmall = 18446744073709551615

# Prevent Stalls from High RAM Pressure
vm.min_free_kbytes = 131072
